### ISSUE TITLE
licence for oled scripts

### ISSUE THREAD

**Issue by jchassin** [audiophonics/Pydpiper-Raspdac#2]
Hi all, I have found on moode distrib the following scripts : 
fonts                 raspdac_oled_request_mpd.py     raspdac_oled_screen_frames.py  README.md
ohOled.service        raspdac_oled_request_os.py      raspdac_oled_screen_menu.py
raspdac_oled_main.py  raspdac_oled_screen_display.py  raspdac_oled_telecommand.py

There are no mention of any licences on these scripts, I would like to modify them and stores them on github to be used with Linn Openhome software, would you authorize me to do so ?

Tks,
Jean

**Comment by audiophonics** [comment]
Hello, Most of the work has been done by Dhrone, we only adapted template for our Raspdac product on this version.
You can ask him, but I think there is no problem with that.
https://github.com/dhrone/pydPiper
